spring:
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE # ack-mode: RECORD, BATCH, TIME, COUNT, COUNT_TIME, MANUAL, MANUAL_IMMEDIATE
    consumer:
      enable-auto-commit: false # true -> commit by auto.commit.interval.ms
